"""MOSAIC Provider-Agnostic LLM Models and Exception Definitions.

Defines generic Pydantic request and response contracts for LLM interactions,
ensuring total decoupling from provider-specific SDKs.
"""

from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, ConfigDict


class LLMError(Exception):
    """Base exception for all MOSAIC LLM abstraction failures."""
    pass


class LLMConfigurationError(LLMError):
    """Raised when an invalid or missing LLM configuration is encountered."""
    pass


class LLMResponseError(LLMError):
    """Raised when an LLM provider returns an invalid or malformed response."""
    pass


class LLMRequest(BaseModel):
    """Generic, provider-agnostic request payload for LLM operations."""
    system_prompt: str = Field(..., description="System instructions guiding LLM behavior.")
    user_prompt: str = Field(..., description="User input message or context.")
    structured_schema: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional JSON Schema specification for structured output generation."
    )
    temperature: float = Field(default=0.0, ge=0.0, le=2.0)
    max_tokens: Optional[int] = Field(default=None, gt=0)
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Generic runtime parameters.")

    model_config = ConfigDict(frozen=True)


class LLMResponse(BaseModel):
    """Generic, provider-agnostic response container for LLM outputs."""
    content: str = Field(..., description="Raw text generated by the model.")
    structured_output: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Parsed structured JSON output if requested in LLMRequest."
    )
    provider_name: str = Field(..., description="Identifier of the provider executing the request.")
    model_name: str = Field(..., description="Identifier of the specific model invoked.")
    usage_info: Dict[str, Any] = Field(default_factory=dict, description="Token or resource usage statistics.")
    finish_reason: str = Field(default="stop", description="Completion status (e.g. stop, length).")

    model_config = ConfigDict(frozen=True)
