"""
tools/rescore_phase_7e_conflict_gold_v2.py

Offline rescore script for MOSAIC Phase 7E Design C v2 benchmark.

Reads:
  - Phase 7E gold-v2 dataset: tests/fixtures/research_dataset/v1_natural_language_phase7e_gold_v2/cases.json
  - Original Phase 7E v2 results: evaluation_results/phase_7e_design_c_v2/results.json

Writes:
  - Rescore output: evaluation_results/phase_7e_design_c_v2_conflict_gold_v2/conflict_rescore.json
  - Documentation: evaluation_results/phase_7e_design_c_v2_conflict_gold_v2/README.md

Strict Offline Guarantee:
  - Makes 0 LLM calls, 0 network requests, 0 API calls.
  - Leaves original results.json and v1 cases.json completely untouched.
"""

import hashlib
import json
from pathlib import Path
from typing import Dict, Any, List

# ── Paths & Metadata ──────────────────────────────────────────────────────────
PROVENANCE = {
    "original_benchmark_commit": "1979573",
    "documentation_commit": "79c07c6",
    "provider": "ollama",
    "model": "llama3.2:latest",
    "original_benchmark_design": "Design C / shared-context evaluation",
    "gold_version": "Phase 7E conflict-gold-v2",
    "analysis_type": "Offline derived analysis",
    "notes": "No new LLM inference was performed. This artifact was generated by comparing existing Phase 7E MOSAIC predictions against the versioned Phase 7E conflict-gold-v2 annotations."
}

V1_CASES_PATH = Path("tests/fixtures/research_dataset/v1_natural_language/cases.json")
GOLD_V2_CASES_PATH = Path("tests/fixtures/research_dataset/v1_natural_language_phase7e_gold_v2/cases.json")
V2_RESULTS_PATH = Path("evaluation_results/phase_7e_design_c_v2/results.json")

OUTPUT_DIR = Path("evaluation_results/phase_7e_design_c_v2_conflict_gold_v2")
OUTPUT_RESCORE_PATH = OUTPUT_DIR / "conflict_rescore.json"
OUTPUT_README_PATH = OUTPUT_DIR / "README.md"

CONFLICT_TYPES = [
    "AMBIGUOUS_EVIDENCE",
    "MISSING_DEPENDENCY",
    "PRECONDITION_UNSATISFIED",
    "MUTUALLY_EXCLUSIVE_POSTCONDITION"
]


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def calc_metrics(eval_pairs: List[Dict[str, Any]], gold_key: str, pred_key: str) -> Dict[str, Any]:
    """Calculates macro/global TP, FP, FN, P, R, F1 and per-type metrics for given gold and pred keys."""
    global_tp = global_fp = global_fn = 0
    type_counts = {t: {"tp": 0, "fp": 0, "fn": 0} for t in CONFLICT_TYPES}

    for item in eval_pairs:
        gold_set = set(item[gold_key])
        pred_set = set(item[pred_key])

        # Global aggregate
        tp = len(pred_set & gold_set)
        fp = len(pred_set - gold_set)
        fn = len(gold_set - pred_set)

        global_tp += tp
        global_fp += fp
        global_fn += fn

        # Per conflict type
        for t in CONFLICT_TYPES:
            in_gold = t in gold_set
            in_pred = t in pred_set
            if in_gold and in_pred:
                type_counts[t]["tp"] += 1
            elif in_pred and not in_gold:
                type_counts[t]["fp"] += 1
            elif in_gold and not in_pred:
                type_counts[t]["fn"] += 1

    # Global summary
    p = global_tp / (global_tp + global_fp) if (global_tp + global_fp) > 0 else 1.0
    r = global_tp / (global_tp + global_fn) if (global_tp + global_fn) > 0 else 1.0
    f1 = 2 * p * r / (p + r) if (p + r) > 0 else 0.0

    # Per-type summary
    per_type_metrics = {}
    for t in CONFLICT_TYPES:
        c = type_counts[t]
        c_tp, c_fp, c_fn = c["tp"], c["fp"], c["fn"]
        tp_fp = c_tp + c_fp
        tp_fn = c_tp + c_fn
        tp_p = c_tp / tp_fp if tp_fp > 0 else 1.0
        tp_r = c_tp / tp_fn if tp_fn > 0 else 1.0
        tp_f1 = 2 * tp_p * tp_r / (tp_p + tp_r) if (tp_p + tp_r) > 0 else 0.0
        per_type_metrics[t] = {
            "tp": c_tp,
            "fp": c_fp,
            "fn": c_fn,
            "precision": round(tp_p, 4),
            "recall": round(tp_r, 4),
            "f1": round(tp_f1, 4)
        }

    return {
        "tp": global_tp,
        "fp": global_fp,
        "fn": global_fn,
        "precision": round(p, 4),
        "recall": round(r, 4),
        "f1": round(f1, 4),
        "per_conflict_type": per_type_metrics
    }


def main():
    print("==================================================")
    print("MOSAIC PHASE 7E CONFLICT GOLD V2 OFFLINE RESCORE")
    print("==================================================")

    # 1. Checksums before
    v1_cases_hash = sha256_file(V1_CASES_PATH)
    v2_results_hash = sha256_file(V2_RESULTS_PATH)
    gold_v2_cases_hash = sha256_file(GOLD_V2_CASES_PATH)

    print(f"Original v1 cases SHA256:  {v1_cases_hash}")
    print(f"Original v2 results SHA256:{v2_results_hash}")
    print(f"Gold-v2 cases SHA256:      {gold_v2_cases_hash}")

    # 2. Load Gold-v2 cases
    with open(GOLD_V2_CASES_PATH, encoding="utf-8-sig") as f:
        gold_v2_raw = json.load(f)
    gold_v2_dict = {c["case_id"]: c for c in gold_v2_raw}
    print(f"Loaded {len(gold_v2_dict)} gold-v2 cases.")

    # 3. Load v2 Results
    with open(V2_RESULTS_PATH, encoding="utf-8-sig") as f:
        v2_results_raw = json.load(f)

    mosaic_results = [
        r for r in v2_results_raw.get("per_case_results", [])
        if r.get("system_name") == "mosaic_validated"
    ]
    print(f"Loaded {len(mosaic_results)} completed MOSAIC case results.")

    # Integrity assertion
    for r in mosaic_results:
        assert r["case_id"] in gold_v2_dict, f"Missing case_id {r['case_id']} in gold-v2"

    # 4. Build Evaluation Pairs
    eval_pairs = []
    case_disagreements = []

    for r in mosaic_results:
        cid = r["case_id"]
        g = gold_v2_dict[cid]

        exp_primary = g.get("expected_conflicts", [])
        exp_secondary = g.get("expected_secondary_conflicts", [])
        exp_verdict = g.get("expected_final_verdict")

        pred_primary = r.get("primary_conflicts", [])
        pred_secondary = r.get("secondary_conflicts", [])
        pred_flat = r.get("detected_conflicts", [])
        pred_verdict = r.get("predicted_verdict")

        eval_pairs.append({
            "case_id": cid,
            "gold_primary": exp_primary,
            "pred_primary": pred_primary,
            "gold_secondary": exp_secondary,
            "pred_secondary": pred_secondary,
            "gold_flat": exp_primary,  # Flat gold benchmark uses primary expected_conflicts
            "pred_flat": pred_flat,
            "gold_verdict": exp_verdict,
            "pred_verdict": pred_verdict
        })

        # Check disagreements
        primary_diff = set(exp_primary) != set(pred_primary)
        secondary_diff = set(exp_secondary) != set(pred_secondary)
        verdict_diff = exp_verdict != pred_verdict

        if primary_diff or secondary_diff or verdict_diff:
            case_disagreements.append({
                "case_id": cid,
                "expected_primary": exp_primary,
                "predicted_primary": pred_primary,
                "expected_secondary": exp_secondary,
                "predicted_secondary": pred_secondary,
                "expected_verdict": exp_verdict,
                "predicted_verdict": pred_verdict,
                "disagreement_flags": {
                    "primary_disagreement": primary_diff,
                    "secondary_disagreement": secondary_diff,
                    "verdict_disagreement": verdict_diff
                }
            })

    # 5. Compute Metrics
    primary_metrics = calc_metrics(eval_pairs, "gold_primary", "pred_primary")
    secondary_metrics = calc_metrics(eval_pairs, "gold_secondary", "pred_secondary")
    flat_metrics = calc_metrics(eval_pairs, "gold_flat", "pred_flat")

    # 6. Assemble Rescore Output
    rescore_data = {
        "provenance": PROVENANCE,
        "integrity_checksums": {
            "v1_cases_json_sha256": v1_cases_hash,
            "v2_results_json_sha256": v2_results_hash,
            "gold_v2_cases_json_sha256": gold_v2_cases_hash
        },
        "summary_counts": {
            "total_dataset_cases": len(gold_v2_dict),
            "completed_mosaic_cases": len(mosaic_results),
            "failed_cases": v2_results_raw.get("failed_cases_count", 3),
            "evaluated_conflict_cases": len(mosaic_results)
        },
        "metrics": {
            "primary_conflicts": primary_metrics,
            "secondary_conflicts": secondary_metrics,
            "flat_conflicts": flat_metrics
        },
        "case_disagreements": case_disagreements
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_RESCORE_PATH, "w", encoding="utf-8") as f:
        json.dump(rescore_data, f, indent=2)
    print(f"Wrote rescore JSON to: {OUTPUT_RESCORE_PATH}")

    # 7. Write README.md
    readme_content = f"""# MOSAIC Phase 7E Design C v2 — Conflict Gold v2 Offline Rescore

## Overview

"No new LLM inference was performed. This artifact was generated by comparing existing Phase 7E MOSAIC predictions against the versioned Phase 7E conflict-gold-v2 annotations."

This directory contains a derived, offline rescore of MOSAIC's Phase 7E Design C v2 benchmark results evaluated against the revised **Phase 7E conflict-gold-v2** annotations (`tests/fixtures/research_dataset/v1_natural_language_phase7e_gold_v2/cases.json`).

---

## Provenance & Integrity

- **Original Benchmark Commit**: `{PROVENANCE['original_benchmark_commit']}`
- **Documentation Commit**: `{PROVENANCE['documentation_commit']}`
- **Provider / Model**: `{PROVENANCE['provider']}` / `{PROVENANCE['model']}`
- **Evaluation Design**: `{PROVENANCE['original_benchmark_design']}`
- **Gold Dataset Version**: `{PROVENANCE['gold_version']}`
- **Original `v1/cases.json` SHA256**: `{v1_cases_hash}`
- **Original `phase_7e_design_c_v2/results.json` SHA256**: `{v2_results_hash}`
- **Conflict Gold v2 `cases.json` SHA256**: `{gold_v2_cases_hash}`

---

## Rescore Summary Metrics (36 Completed Cases)

### A. Primary Conflicts (Routing-Determining Root Semantic Conflicts)
- **Precision**: {primary_metrics['precision'] * 100:.2f}%
- **Recall**: {primary_metrics['recall'] * 100:.2f}%
- **F1 Score**: **{primary_metrics['f1'] * 100:.2f}%**
- **TP / FP / FN**: {primary_metrics['tp']} / {primary_metrics['fp']} / {primary_metrics['fn']}

### B. Secondary Conflicts (Downstream Structural Cascades)
- **Precision**: {secondary_metrics['precision'] * 100:.2f}%
- **Recall**: {secondary_metrics['recall'] * 100:.2f}%
- **F1 Score**: **{secondary_metrics['f1'] * 100:.2f}%**
- **TP / FP / FN**: {secondary_metrics['tp']} / {secondary_metrics['fp']} / {secondary_metrics['fn']}

### C. Flat Detected Conflicts (Supplementary Aggregate Metric)
- **Precision**: {flat_metrics['precision'] * 100:.2f}%
- **Recall**: {flat_metrics['recall'] * 100:.2f}%
- **F1 Score**: **{flat_metrics['f1'] * 100:.2f}%**
- **TP / FP / FN**: {flat_metrics['tp']} / {flat_metrics['fp']} / {flat_metrics['fn']}

---

## Case Disagreements
Total cases with disagreement between Gold-v2 expectations and MOSAIC predictions: **{len(case_disagreements)}**.
(See `conflict_rescore.json` for full case-level breakdown).
"""

    with open(OUTPUT_README_PATH, "w", encoding="utf-8") as f:
        f.write(readme_content)
    print(f"Wrote README to: {OUTPUT_README_PATH}")

    # 8. Post-rescore integrity check
    assert sha256_file(V1_CASES_PATH) == v1_cases_hash, "V1 cases file changed!"
    assert sha256_file(V2_RESULTS_PATH) == v2_results_hash, "V2 results file changed!"
    assert sha256_file(GOLD_V2_CASES_PATH) == gold_v2_cases_hash, "Gold-v2 cases file changed!"
    print("Post-rescore checksum verification: PASSED (All original files unchanged).")


if __name__ == "__main__":
    main()
